baseURL = "https://myblog.midsummerproudsun.workers.dev/"
title = "阳光传感器"
languageCode = "zh-cn"

[module]
  [[module.imports]]
    path = "github.com/jmfergeau/hugo.386"

[pagination]
  pagerSize = 10

[params]
  mainpagetitle = "盛夏骄阳"
  mainpagesubtitle = "日之所照·万象成集"
  mainpagedesc = "这里是阳光传感器，一块收集日光，转化热爱的太阳能板。"

  copyrightname = "盛夏骄阳"
  showhugo = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/post/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 30